# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 05:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userstates', '0001_initial'),
        ('states', '0001_initial'),
        ('chapters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestsTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapters.Chapter')),
                ('resultant_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userstates.UserCurrentNode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op1', models.BooleanField(default=False)),
                ('op2', models.BooleanField(default=False)),
                ('op3', models.BooleanField(default=False)),
                ('op4', models.BooleanField(default=False)),
                ('integer_type_submission', models.CharField(blank=True, max_length=200)),
                ('time_of_sumbission', models.CharField(blank=True, max_length=200)),
                ('submitted_by_user', models.BooleanField(default=False)),
                ('correctans', models.BooleanField(default=False)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='states.State')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
