# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 07:50
from __future__ import unicode_literals

import chapters.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('gaurd', models.CharField(choices=[('algebra', 'Algebra'), ('calculus', 'Calculas'), ('geometry', 'Geometry'), ('trigo', 'Trigonometry'), ('cartgeo', 'Cartesian-Geometry'), ('others', 'Others')], default='others', max_length=120)),
                ('standard', models.IntegerField(default='10')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=chapters.models.upload_image_path_chapters)),
            ],
            options={
                'db_table': 'Chapter',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=40000)),
                ('qimage', models.FileField(blank=True, null=True, upload_to=chapters.models.upload_image_path_questions)),
                ('answer', models.TextField(blank=True, max_length=40000)),
                ('aimage', models.FileField(blank=True, null=True, upload_to=chapters.models.upload_image_path_questions)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('content1', models.TextField(max_length=30000)),
                ('image1', models.FileField(blank=True, null=True, upload_to=chapters.models.upload_image_path_topics)),
                ('content2', models.TextField(blank=True, max_length=30000)),
                ('image2', models.FileField(blank=True, null=True, upload_to=chapters.models.upload_image_path_topics)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapters.Chapter')),
            ],
            options={
                'db_table': 'Topic',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapters.Topic'),
        ),
    ]
