# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-26 11:30
from __future__ import unicode_literals

import chapters.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('gaurd', models.CharField(choices=[('algebra', 'Algebra'), ('calculus', 'Calculas'), ('geometry', 'Geometry'), ('trigo', 'Trigonometry'), ('cartgeo', 'Cartesian-Geometry'), ('others', 'Others')], default='others', max_length=120)),
                ('standard', models.IntegerField(default='10')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=chapters.models.upload_image_path_chapters)),
            ],
            options={
                'db_table': 'Chapter',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('level', models.IntegerField(default=0)),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='questions')),
                ('text_option1', models.CharField(blank=True, max_length=200)),
                ('text_option2', models.CharField(blank=True, max_length=200)),
                ('text_option3', models.CharField(blank=True, max_length=200)),
                ('text_option4', models.CharField(blank=True, max_length=200)),
                ('op1', models.BooleanField(default=False)),
                ('op2', models.BooleanField(default=False)),
                ('op3', models.BooleanField(default=False)),
                ('op4', models.BooleanField(default=False)),
                ('time_in_minutes', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('integer_type', models.BooleanField(default=False)),
                ('single_option', models.BooleanField(default=False)),
                ('integer_type_answer', models.CharField(blank=True, max_length=200)),
                ('answer_image', models.ImageField(blank=True, null=True, upload_to='answers')),
                ('answer_text', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('content1', models.TextField(max_length=30000)),
                ('image1', models.FileField(blank=True, null=True, upload_to=chapters.models.upload_image_path_topics)),
                ('content2', models.TextField(blank=True, max_length=30000)),
                ('image2', models.FileField(blank=True, null=True, upload_to=chapters.models.upload_image_path_topics)),
                ('total_test_time_in_minutes', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapters.Chapter')),
            ],
            options={
                'db_table': 'Topic',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapters.Topic'),
        ),
    ]
