# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0002_auto_20180820_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='aimage',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='qimage',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='answers'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='integer_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='integer_type_answer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='op1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='op2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='op3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='op4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='qno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='questions'),
        ),
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='single_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='text_option1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='text_option2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='text_option3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='text_option4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='time_in_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=200),
        ),
    ]
