# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0003_auto_20180821_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='total_test_time_in_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
