# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0004_topic_total_test_time_in_minutes'),
        ('chapters', '0002_auto_20180821_0201'),
    ]

    operations = [
    ]
