# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0005_merge_20180821_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='qno',
        ),
    ]
