# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0006_remove_question_qno'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qno',
            field=models.IntegerField(default=0),
        ),
    ]
