# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-26 11:30
from __future__ import unicode_literals

import content.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to=content.models.upload_image_path_content)),
                ('image2', models.FileField(blank=True, null=True, upload_to=content.models.upload_image_path_content)),
                ('credit', models.PositiveSmallIntegerField(default='1', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('time', models.IntegerField()),
                ('tag', models.CharField(blank=True, max_length=15, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='states.State')),
            ],
        ),
        migrations.CreateModel(
            name='Illustration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('answer', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to=content.models.upload_image_path_illus)),
                ('image2', models.FileField(blank=True, null=True, upload_to=content.models.upload_image_path_illus)),
                ('credit', models.PositiveSmallIntegerField(default='3', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('time', models.IntegerField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Content')),
            ],
        ),
    ]
