# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 07:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20180817_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='credit',
            field=models.PositiveSmallIntegerField(default='1', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='illustration',
            name='credit',
            field=models.PositiveSmallIntegerField(default='3', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
