# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20180819_0750'),
        ('content', '0003_auto_20180819_1314'),
    ]

    operations = [
    ]
