# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import questions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=6600)),
                ('question_image', models.FileField(blank=True, null=True, upload_to=questions.models.upload_image_path_questions)),
                ('option1', models.CharField(blank=True, max_length=2200)),
                ('option2', models.CharField(blank=True, max_length=2200)),
                ('option3', models.CharField(blank=True, max_length=2200)),
                ('option4', models.CharField(blank=True, max_length=2200)),
                ('op1', models.BooleanField(default=False)),
                ('op2', models.BooleanField(default=False)),
                ('op3', models.BooleanField(default=False)),
                ('op4', models.BooleanField(default=False)),
                ('time', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('integer_type', models.BooleanField(default=False)),
                ('single_option', models.BooleanField(default=False)),
                ('integeral_answer', models.CharField(blank=True, max_length=100)),
                ('answer_image', models.FileField(blank=True, null=True, upload_to=questions.models.upload_image_path_questions)),
                ('answer_text', models.TextField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='states.State')),
            ],
        ),
    ]
