# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 05:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginer', 'Beginer'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=60)),
                ('significance', models.IntegerField(blank=True, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapters.Chapter')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TempActiveNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapters.Chapter')),
                ('node', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='states.Node')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCurrentNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incorrect', models.IntegerField(default=0)),
                ('timedate', models.DateTimeField(auto_now_add=True, null=True)),
                ('chapter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chapters.Chapter')),
                ('node', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='states.Node')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
