# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 08:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chapters', '0005_merge_20180821_0813'),
        ('states', '0003_auto_20180819_0756'),
        ('userstates', '0002_auto_20180821_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapters.Chapter')),
                ('node', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='states.Node')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
