# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstates', '0003_tempstate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempState',
            new_name='TempActiveNode',
        ),
    ]
