# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 08:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userstates', '0006_auto_20180822_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proficiency',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tempactivenode',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapters.Chapter'),
        ),
        migrations.AlterField(
            model_name='tempactivenode',
            name='node',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='states.Node'),
        ),
        migrations.AlterField(
            model_name='tempactivenode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
