# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0005_merge_20180821_0813'),
        ('userstates', '0008_auto_20180822_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercurrentnode',
            name='chapter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chapters.Chapter'),
        ),
    ]
