# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-17 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('topic', models.CharField(max_length=222)),
                ('rate', models.IntegerField()),
                ('time', models.IntegerField()),
                ('tag', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
