# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0002_auto_20180819_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapters.Topic'),
        ),
    ]
